export const BLOG_CATS = ['All', 'Mobile', 'Web', 'Design', 'Marketing', 'Cloud'];

export const POSTS = [
  {
    id: 1,
    title: 'Why Your Business Needs a Mobile App in 2025',
    cat: 'Mobile',
    excerpt: 'With over 6 billion smartphone users worldwide, having a mobile app is no longer a luxury — it\'s a necessity. Discover why businesses that invest in mobile apps see up to 3x more customer engagement.',
    author: 'Arjun Mehta',
    role: 'CEO & Co-founder',
    init: 'AM',
    date: 'May 2, 2026',
    read: '5 min read',
    featured: true,
    accent: '#3D6CFF',
    body: [
      { type: 'p', text: 'We are living in a mobile-first world. Your customers are on their phones for an average of 4–5 hours a day — and if your business isn\'t there, your competitors will be. A mobile app isn\'t just a digital product; it\'s a direct channel to your customers, available 24/7.' },
      { type: 'h3', text: 'The Numbers Don\'t Lie' },
      { type: 'p', text: 'Businesses with a dedicated mobile app report up to 3x higher customer engagement compared to those relying solely on websites. Push notifications alone have an open rate of 90% — compared to just 20% for email. And with mobile commerce (m-commerce) accounting for over 70% of global e-commerce, ignoring mobile means leaving serious revenue on the table.' },
      { type: 'h3', text: 'What a Mobile App Does for Your Business' },
      { type: 'list', items: [
        'Direct access to your customers with push notifications',
        'Faster, smoother experience than mobile websites',
        'Builds brand loyalty through a dedicated presence on their device',
        'Enables offline functionality so users stay engaged without internet',
        'Collects valuable user data and behaviour analytics',
        'Opens new revenue streams through in-app purchases or subscriptions',
      ]},
      { type: 'h3', text: 'When is the Right Time?' },
      { type: 'p', text: 'The right time to build a mobile app is when you have a clear user need that a website cannot solve as well. If your customers need to interact with your product frequently, access it on the go, or if you want to send targeted communications — a mobile app is the answer.' },
      { type: 'p', text: 'At Appnity Technologies, we\'ve built mobile apps for healthcare, logistics, fintech, and e-commerce businesses. The one thing they all have in common: after launch, they wondered why they didn\'t do it sooner.' },
    ],
  },
  {
    id: 2,
    title: 'Flutter vs React Native: Which One Should You Choose?',
    cat: 'Mobile',
    excerpt: 'Both Flutter and React Native are excellent choices for cross-platform development, but which one is right for your project? We break down the key differences in performance, ecosystem, and developer experience.',
    author: 'Priya Sharma',
    role: 'CTO & Co-founder',
    init: 'PS',
    date: 'Apr 28, 2026',
    read: '7 min read',
    featured: false,
    accent: '#3D6CFF',
    body: [
      { type: 'p', text: 'Cross-platform mobile development has come a long way. Today, Flutter and React Native are the two dominant frameworks — and choosing between them is one of the first decisions you\'ll make when starting a mobile project. Both are excellent, but they suit different needs.' },
      { type: 'h3', text: 'Flutter: Google\'s UI Toolkit' },
      { type: 'p', text: 'Flutter uses Dart and renders its own UI components using the Skia/Impeller graphics engine. This means pixel-perfect consistency across iOS and Android — your app looks exactly the same on both platforms. Flutter is exceptional for performance-heavy apps, complex animations, and custom UI designs.' },
      { type: 'h3', text: 'React Native: JavaScript All the Way' },
      { type: 'p', text: 'React Native uses JavaScript and bridges to native components. If your team already knows React, the learning curve is minimal. It has a massive ecosystem, and since it uses actual native components, it feels more "native" in some respects. Meta, Microsoft, and Shopify use React Native in production.' },
      { type: 'h3', text: 'How to Choose' },
      { type: 'list', items: [
        'Choose Flutter if you need custom UI, animations, or pixel-perfect design control',
        'Choose React Native if your team knows JavaScript/React and wants faster onboarding',
        'Flutter has better raw performance; React Native has a larger community',
        'Both support iOS, Android, and increasingly web and desktop',
        'Flutter is better for greenfield projects; React Native integrates better with existing apps',
      ]},
      { type: 'h3', text: 'Our Recommendation' },
      { type: 'p', text: 'At Appnity, we use both — and we choose based on the project requirements, not preference. For most client projects where design quality is paramount, we lean toward Flutter. For teams with existing JavaScript expertise or React codebases, React Native is the natural choice. The good news: both are production-ready and battle-tested.' },
    ],
  },
  {
    id: 3,
    title: '10 UI/UX Principles That Drive User Engagement',
    cat: 'Design',
    excerpt: 'Great design isn\'t just about aesthetics — it\'s about creating experiences that feel intuitive and keep users coming back. Here are 10 proven UI/UX principles we apply to every product we build.',
    author: 'Rahul Verma',
    role: 'Head of Design',
    init: 'RV',
    date: 'Apr 20, 2026',
    read: '6 min read',
    featured: false,
    accent: '#B14CFF',
    body: [
      { type: 'p', text: 'Good design is invisible. When a product is designed well, users don\'t think about the interface — they just accomplish what they came to do. Bad design, on the other hand, creates friction, frustration, and ultimately, churn. Here are the 10 principles our design team swears by.' },
      { type: 'h3', text: 'The 10 Principles' },
      { type: 'list', items: [
        'Clarity over cleverness — users should never wonder what a button does',
        'Consistency — same actions should produce same results, everywhere',
        'Feedback — every action needs a visible response (loading, success, error)',
        'Hierarchy — guide the eye to what matters most on every screen',
        'Whitespace — breathing room is not wasted space, it\'s clarity',
        'Mobile-first — design for the smallest screen first, then scale up',
        'Accessibility — at least 1 in 4 users has a disability; design for everyone',
        'Speed — perceived performance is part of the design; skeleton screens, optimistic UI',
        'Error prevention — design so mistakes are hard to make in the first place',
        'Delight — small moments of joy (micro-animations, illustrations) build emotional connection',
      ]},
      { type: 'h3', text: 'Why This Matters for Your Business' },
      { type: 'p', text: 'A well-designed product doesn\'t just look good in screenshots — it converts better, retains users longer, and generates better reviews. Studies consistently show that every $1 invested in UX returns $100 in ROI. Design is not a cost; it\'s an investment.' },
      { type: 'p', text: 'At Appnity, every product we build goes through a rigorous design process — from user research and wireframes to interactive prototypes and usability testing — before a single line of code is written.' },
    ],
  },
  {
    id: 4,
    title: 'How to Build a Scalable Web App with React and Node.js',
    cat: 'Web',
    excerpt: 'Building for scale from day one saves you from costly rewrites later. We walk through the architecture patterns, database strategies, and deployment practices we use to build web apps that grow with your business.',
    author: 'Neha Kapoor',
    role: 'Head of Engineering',
    init: 'NK',
    date: 'Apr 15, 2026',
    read: '8 min read',
    featured: false,
    accent: '#7A4CFF',
    body: [
      { type: 'p', text: 'Scalability is one of those things that seems theoretical until your app goes viral and crashes. We\'ve seen it happen — and we\'ve also helped teams recover from it. The key is making the right architectural decisions early, without over-engineering for problems you don\'t have yet.' },
      { type: 'h3', text: 'Frontend: React Done Right' },
      { type: 'p', text: 'React is our primary frontend framework for web apps. We structure projects with clear separation of concerns — components, hooks, services, and state management are all in their own lanes. We use React Query for server state, Zustand or Redux Toolkit for client state, and TypeScript for everything.' },
      { type: 'h3', text: 'Backend: Node.js + Express or NestJS' },
      { type: 'p', text: 'For the backend, we use Node.js with either Express (for simpler APIs) or NestJS (for complex enterprise applications). NestJS gives us a clear structure with dependency injection, decorators, and built-in support for microservices.' },
      { type: 'h3', text: 'Database Strategy' },
      { type: 'list', items: [
        'PostgreSQL for relational data — reliable, powerful, and scales well',
        'Redis for caching and session management',
        'Elasticsearch for full-text search when needed',
        'Use connection pooling (PgBouncer) from day one',
        'Plan your indexing strategy before you have millions of rows',
      ]},
      { type: 'h3', text: 'Deployment & Infrastructure' },
      { type: 'p', text: 'We containerise everything with Docker and deploy to AWS or Google Cloud using managed services. This means auto-scaling, zero-downtime deployments, and infrastructure that grows with your traffic automatically — without you having to think about servers.' },
    ],
  },
  {
    id: 5,
    title: 'Digital Marketing Strategies That Actually Work in 2026',
    cat: 'Marketing',
    excerpt: 'SEO, PPC, social media, content — there\'s a lot of noise in digital marketing. We cut through it and share the strategies that consistently deliver ROI for our clients across different industries.',
    author: 'Deepa Nair',
    role: 'Head of Marketing',
    init: 'DN',
    date: 'Apr 10, 2026',
    read: '6 min read',
    featured: false,
    accent: '#0B9E6A',
    body: [
      { type: 'p', text: 'Digital marketing has never been more powerful — or more crowded. Every business is online now, which means standing out requires more than just running ads. The strategies that work in 2026 are about building genuine connections, providing real value, and using data to make smarter decisions.' },
      { type: 'h3', text: '1. SEO is Still King — But It\'s Changed' },
      { type: 'p', text: 'Search engine optimisation is no longer just about keywords. Google\'s algorithm now prioritises experience, expertise, authority, and trust (E-E-A-T). Long-form, genuinely helpful content consistently outperforms thin keyword-stuffed pages. Invest in content that actually answers your customers\' questions.' },
      { type: 'h3', text: '2. Performance Marketing with Clear Attribution' },
      { type: 'p', text: 'Google Ads and Meta Ads still deliver excellent ROI when run correctly. The key is attribution — knowing exactly which campaign drove which conversion. With iOS privacy changes, server-side tracking has become essential. Set this up before you spend a rupee on paid ads.' },
      { type: 'h3', text: '3. Social Media That Connects' },
      { type: 'list', items: [
        'LinkedIn for B2B — share thought leadership, case studies, and team culture',
        'Instagram for visual brands — consistent aesthetic, Reels for reach',
        'YouTube for education — how-to content builds trust and ranks on Google',
        'Engage with comments and DMs — algorithms reward accounts that spark conversation',
      ]},
      { type: 'h3', text: '4. Email Marketing: The Highest ROI Channel' },
      { type: 'p', text: 'Email consistently delivers $42 ROI for every $1 spent. Build your list, segment it, and send content that\'s relevant to each segment. Automation sequences for onboarding, cart abandonment, and re-engagement are non-negotiable for any serious business.' },
    ],
  },
  {
    id: 6,
    title: 'Why SMEs Are Moving to Cloud: A Practical Guide',
    cat: 'Cloud',
    excerpt: 'Cloud computing is no longer just for large enterprises. Small and medium businesses are seeing huge gains in flexibility, cost savings, and security. Here\'s everything you need to know before making the move.',
    author: 'Vikram Singh',
    role: 'Head of Cloud',
    init: 'VS',
    date: 'Apr 5, 2026',
    read: '7 min read',
    featured: false,
    accent: '#3D6CFF',
    body: [
      { type: 'p', text: 'Five years ago, "moving to the cloud" was a complex, expensive undertaking reserved for large companies with dedicated IT teams. Today, it\'s something any business can do — and the ones that do it are seeing measurable advantages over those that don\'t.' },
      { type: 'h3', text: 'The Core Benefits' },
      { type: 'list', items: [
        'Pay only for what you use — no expensive hardware that sits idle',
        'Scale up or down instantly based on demand',
        'Access your systems from anywhere in the world',
        'Enterprise-grade security and compliance out of the box',
        'Automatic backups and disaster recovery',
        'Reduced IT maintenance burden on your team',
      ]},
      { type: 'h3', text: 'Choosing the Right Cloud Provider' },
      { type: 'p', text: 'AWS is the most feature-rich and has the largest ecosystem. Google Cloud excels at data analytics and machine learning. Azure integrates best with Microsoft 365 and Windows-based systems. For most SMEs, the differences are minor — what matters more is the managed services available in your region and your team\'s familiarity.' },
      { type: 'h3', text: 'Common Mistakes to Avoid' },
      { type: 'p', text: 'The biggest mistake businesses make when moving to cloud is "lift and shift" — simply moving existing on-premise setups to the cloud without re-architecting them for cloud-native benefits. This results in higher costs with fewer benefits. A proper cloud migration starts with a clear strategy.' },
      { type: 'h3', text: 'How Appnity Can Help' },
      { type: 'p', text: 'Our cloud team handles everything from initial assessment and migration planning to deployment, monitoring, and ongoing optimisation. We\'ve helped businesses in logistics, healthcare, and e-commerce move to cloud and reduce their infrastructure costs by 40–60% while improving reliability.' },
    ],
  },
  {
    id: 7,
    title: 'The Power of Progressive Web Apps for Your Business',
    cat: 'Web',
    excerpt: 'Progressive Web Apps combine the best of web and mobile. They load fast, work offline, and can be installed on any device — without going through an app store. Could a PWA be the right solution for you?',
    author: 'Neha Kapoor',
    role: 'Head of Engineering',
    init: 'NK',
    date: 'Mar 28, 2026',
    read: '5 min read',
    featured: false,
    accent: '#7A4CFF',
    body: [
      { type: 'p', text: 'A Progressive Web App (PWA) is a website that behaves like a native app. It can be installed on your home screen, works offline, sends push notifications, and loads almost instantly — all without being in the App Store or Play Store. For many businesses, PWAs offer the best of both worlds.' },
      { type: 'h3', text: 'Why PWAs Are Growing' },
      { type: 'p', text: 'Twitter, Pinterest, Uber, and Starbucks all have PWAs. After Twitter launched its PWA, they saw a 65% increase in pages per session and a 75% increase in Tweets sent. Starbucks\'s PWA is 99.84% smaller than their iOS app — and works offline for menu browsing and order building.' },
      { type: 'h3', text: 'PWA vs Native App: When to Choose What' },
      { type: 'list', items: [
        'Choose PWA if you need fast time-to-market with cross-platform reach',
        'Choose native if you need device hardware access (camera, GPS, sensors)',
        'PWAs are better for content-heavy apps (news, e-commerce, productivity)',
        'Native apps are better for games or apps requiring intensive graphics',
        'PWAs have lower development and maintenance costs',
      ]},
      { type: 'h3', text: 'The Technical Foundation' },
      { type: 'p', text: 'PWAs are built on three core technologies: Service Workers (for offline and caching), Web App Manifest (for installability), and HTTPS (for security). Modern frameworks like React, Angular, and Vue all have excellent PWA support built in, which makes building one much simpler than it used to be.' },
    ],
  },
  {
    id: 8,
    title: 'Building a Brand Identity That Stands Out',
    cat: 'Design',
    excerpt: 'Your brand is more than a logo — it\'s the entire experience customers have with your business. From colour psychology to typography, we explain the elements that make a brand truly memorable.',
    author: 'Rahul Verma',
    role: 'Head of Design',
    init: 'RV',
    date: 'Mar 20, 2026',
    read: '6 min read',
    featured: false,
    accent: '#B14CFF',
    body: [
      { type: 'p', text: 'Ask most business owners what their brand is and they\'ll point at their logo. But a brand is so much more — it\'s the feeling people get when they interact with your business. It\'s your voice, your colours, your typography, your customer service, your packaging. Everything communicates your brand.' },
      { type: 'h3', text: 'The Elements of a Strong Brand Identity' },
      { type: 'list', items: [
        'Logo — versatile, memorable, and works at any size',
        'Colour palette — primary, secondary, and neutral colours with clear usage rules',
        'Typography — font choices that reflect your brand personality',
        'Tone of voice — how you speak to customers in writing',
        'Imagery style — the types of photos and illustrations you use',
        'Iconography — a consistent visual language for UI and marketing',
      ]},
      { type: 'h3', text: 'Colour Psychology Matters' },
      { type: 'p', text: 'Colour is one of the most powerful tools in branding. Blue communicates trust and professionalism (banks, tech companies). Red communicates energy and urgency (food, retail). Green signals health, nature, and sustainability. Before choosing your brand colours, think about the emotion you want to evoke — not just what looks nice.' },
      { type: 'h3', text: 'Consistency is Everything' },
      { type: 'p', text: 'A brand identity only works if it\'s applied consistently — across your website, social media, packaging, emails, and everything else. This is why we always deliver a brand guidelines document alongside every identity we create. It\'s the rulebook that keeps everything on-brand as your business grows.' },
    ],
  },
  {
    id: 9,
    title: 'AWS vs Google Cloud vs Azure: Choosing the Right Platform',
    cat: 'Cloud',
    excerpt: 'Each major cloud provider has strengths suited to different use cases. We compare pricing, services, and performance to help you pick the right cloud platform for your next project.',
    author: 'Vikram Singh',
    role: 'Head of Cloud',
    init: 'VS',
    date: 'Mar 14, 2026',
    read: '9 min read',
    featured: false,
    accent: '#3D6CFF',
    body: [
      { type: 'p', text: 'AWS, Google Cloud, and Microsoft Azure collectively account for over 65% of the global cloud market. All three are enterprise-grade, reliable, and feature-rich. But they have distinct strengths, pricing models, and ecosystem advantages — and choosing the wrong one can cost you time and money.' },
      { type: 'h3', text: 'Amazon Web Services (AWS)' },
      { type: 'p', text: 'AWS is the market leader with the broadest range of services — over 200 products covering compute, storage, databases, AI/ML, IoT, and more. If you need a specific cloud service, AWS almost certainly has it. It\'s the safe, proven choice for most applications. The downside: the pricing model can be complex, and costs can surprise you if you\'re not monitoring them.' },
      { type: 'h3', text: 'Google Cloud Platform (GCP)' },
      { type: 'p', text: 'Google Cloud is the strongest for data analytics, machine learning, and Kubernetes (Google invented it). If your project involves BigQuery, TensorFlow, or large-scale data processing, GCP is hard to beat. Google\'s global network infrastructure also gives it excellent latency for global applications.' },
      { type: 'h3', text: 'Microsoft Azure' },
      { type: 'p', text: 'Azure integrates seamlessly with Microsoft products — Active Directory, Office 365, Teams, and Windows Server. For businesses already in the Microsoft ecosystem, Azure is the natural extension. It\'s also strong for hybrid cloud scenarios where some infrastructure stays on-premise.' },
      { type: 'h3', text: 'Our Recommendation Framework' },
      { type: 'list', items: [
        'Microsoft-heavy company → Azure',
        'AI/ML or data-intensive workloads → Google Cloud',
        'General applications, startups, or need widest service range → AWS',
        'All three offer competitive pricing — always use the pricing calculator',
        'Consider where your team\'s existing skills lie',
      ]},
    ],
  },
];
